### ISSUE TITLE
flymake-aspell-setup results in void variable flymake-diagnostic-functions

### ISSUE THREAD

**Issue by pablos-here** [leotaku/flycheck-aspell#15]
Hi,

I'm on `emacs 28.2` with the the latest `flymake-aspell`[1] from `MELPA`.  I set up `init.el` per the doc[2].

When I run `(flymake-aspell-setup)`, I get the following error:

`funcall-interactively: Symbol’s value as variable is void: flymake-diagnostic-functions`

Below is a back trace.  Please let me know if any additional data is needed or if I've borked something on my end.  :\

Thank you!

```
Debugger entered--Lisp error: (void-variable flymake-diagnostic-functions)
  flymake-aspell-setup()
  funcall-interactively(flymake-aspell-setup)
  apply(funcall-interactively flymake-aspell-setup nil)
  repeat-complex-command(1)
  funcall-interactively(repeat-complex-command 1)
  call-interactively(repeat-complex-command nil nil)
  command-execute(repeat-complex-command)
```

### References
1. Version - `flymake-aspell-20221025.1844`
2. `init.el` settings:
```
(setq ispell-dictionary "en_US")
(setq ispell-program-name "aspell")
(setq ispell-silently-savep t)
```

**Comment by leotaku** [comment]
This was caused by me not explicitly requiring the flymake package in flymake-aspell. You could have fixed the issue yourself by adding `(require 'flymake)` before calling `flymake-aspell-setup`, but the commit I've just pushed should fix the issue for all users.

Thanks for reporting and feel free to reopen the issue if my change does not fix the problem for you!

**Comment by pablos-here** [comment]
Hi Leo,

Thank you for the quick response.  Resolved!

I'm very new to `emacs` `elisp` so you're giving me way too much credit to think I could have resolved the issue!  :)
